---
#playbook to fetch CentOS7 image (for Nutanix AHV) to use with the 3-tier Task application
- name: Fetch disk image for Nutanix AHV
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/vars.yaml
  vars:
    pc: "{{ nutanix_host }}"                  #EDIT for your environment - see vars/vars.yaml
    pc_user: "{{ nutanix_username }}"         #EDIT for your environment
    pc_password: "{{ nutanix_password }}"    #EDIT for your environment
    new_image_name: "Windows2019.qcow2"
    image_description: "Windows Server 2019 image for 3-tier (on prem NTNX + AWS) Task app"
    image_source_uri: "http://10.42.194.11/workshop_staging/Windows2019.qcow2" #assumes INTERNAL nutanix HPOC, build your own if you need to -  see comments in main playbook
    api_uri: "{{ 'https://' + pc + ':9440/api/nutanix/v3/images' }}"


  tasks:

  - name: Get a list (json) of all the images known to the Prism Central
    local_action:
      module: uri
      url: "{{ api_uri + '/list' }}"
      method: POST
      url_username: "{{ pc_user }}"
      url_password: "{{ pc_password }}"
      validate_certs: no
      return_content: yes
      status_code: 200
      body_format: json
      body: "{}"
      force_basic_auth: yes
    check_mode: false
    register: result

  - name: Show result
    debug:
      msg: "{{ result.json }}"
    check_mode: false

  - name: Pull the target image into Prism Central
    local_action:
      module: uri
      url: "{{ api_uri }}"
      method: POST
      url_username: "{{ pc_user }}"
      url_password: "{{ pc_password }}"
      validate_certs: no
      return_content: yes
      status_code: 202
      body_format: json
      body: |
            {
              "spec":{
                  "name":"{{ new_image_name }}",
                  "resources":{
                    "image_type":"DISK_IMAGE",
                    "source_uri":"{{ image_source_uri }}"
                  },
                  "description":"{{ image_description }}"
              },
              "metadata":{
                  "kind":"image"
              }
            }
      force_basic_auth: yes
    check_mode: false
    register: result

  - name: Show result of the new image call - result is returned quickly - upload will take a few minutes, maybe 10 or more minutes
    debug:
      msg: "{{ result.json }}"
    check_mode: false